### ISSUE TITLE
Nextcloud sync does not works with android app

### ISSUE THREAD

**Issue by adocampo** [PhieF/CarnetNextcloud#26]
Now list feature is working on 0.12.0, I was trying to use Carnet as my main note-taking application.

I installed CarnetNextcloud and Carnet for android, then, I created a test note on Nextcloud and configured Carnet on Android to connect to my Nextcloud instance. So far, no problem or error, but I cannot see the note on Carnet on Android.

I tapped on "Sync with cloud storage" on Android app, but it does not seems to sync nor returns any error. Don't know if I'm doing something wrong or that message in Nextcloud logs have some meaning for you

> 
> [PHP] Error: fclose(): supplied resource is not a valid stream resource at /var/www/html/custom_apps/carnet/lib/Controller/NoteController.php#416
> 
> POST /index.php/apps/carnet/notes/metadata
> from 172.28.0.1 by malevolent at 2019-01-05T18:16:18+00:00

**Comment by PhieF** [comment]
Hi ! 

This bug seems more related with the Android app

can you please reopen it here ?

https://github.com/PhieF/CarnetAndroid/issues


Have you tried to "pull" to refresh sync on the android side ? (pull the note list down until you see a refresh animation) 
when connecting to your server, you didn't get any error ? 
If you want you can create me test account so as I can try it on my side,

thanks.

I'm working on a new way to get sync done on android, that will go through the android nextcloud app. It should fix most of sync issues but it's not ready yet !

**Comment by adocampo** [comment]
Yes, I forgot to say I also refreshed on the android side by pulling down both in "Recent" and "Browse", but it didn't work either.

PS: Opened the issue on the proper repo. We can close this.
